### ISSUE TITLE
Move to an MVP structure

### ISSUE THREAD

**Issue by beetdemguise** [beetdemguise/website#14]
We already have `views` and `models` so it'll be easy to adapt to using `presenters`.

Now the real question is: 'How much should we stick to presenter-first structure?`. Presenter-first dictates all private functions in the presenters. In order to implement this we'll need to also implement signals and slots (something like [Pyside's implementation](http://zetcode.com/gui/pysidetutorial/eventsandsignals/)).

I'll most like do as such, mainly for practice.

**Comment by TheReviewers** [comment]
Where am i?

**Comment by beetdemguise** [comment]
Where aren't you? :)

**Comment by TheReviewers** [comment]
I Was in bee2 ... now im here...

is this even portal related?

**Comment by beetdemguise** [comment]
No where near. I know Ben and am 'part' of the bee2 repo (however didn't really contribute after the VERY early stages). So maybe you had a few errant clicks?

**Comment by TheReviewers** [comment]
What have  you done for bee2?

**Comment by beetdemguise** [comment]
Ben talked to me about it updating the beemod before any code was written. I don't think I actually touched the code. I __may__ have done some code review on like the first comment. I honestly don't remember; it's been like 2 years. :)

**Comment by TheReviewers** [comment]
Well what is this about?

and how did i get here

**Comment by beetdemguise** [comment]
It's my personal website I'm writing. I'd imagine you accidentally clicked my avatar on the right side of the screen and then got here somehow.

Unless github is doing a `"Here's an issue you may like"` thing.

**Comment by TheReviewers** [comment]
I only use github for BEE2

**Comment by beetdemguise** [comment]
Welp, somehow you got here. :)

**Comment by TheReviewers** [comment]
well*

**Comment by beetdemguise** [comment]
Naw, I'm meant to say 'welp' 👍

**Comment by TheReviewers** [comment]
Ok :+1:

**Comment by TheReviewers** [comment]
Please return to the bee2 community <3

**Comment by beetdemguise** [comment]
I've thought about it since I've upgraded my personal coding environment recently :)

**Comment by TheReviewers** [comment]
:)

**Comment by BenVlodgi** [comment]
I also haven't hardly touched this version of the BEE2
It has all been teamspen210

**Comment by TheReviewers** [comment]
How did you find this @BenVlodgi XD

**Comment by BenVlodgi** [comment]
@beetdemguise is my friend

**Comment by TheReviewers** [comment]
Good!



 ( Convince him to go back to bee2 XD)

**Comment by TheReviewers** [comment]
x)
